
---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - apt:
        name: vim
    
   - name: "Check if vim is installed"
     package_facts:
     manager: "auto"
  
   - name: "Apache result"
     debug:
       msg: "Apache found"
     when: "'vim' in ansible_facts.packages"
    
    - name: "vim result"
      debug:
        msg: "vim NOT found"
      when: "'vim' not in ansible_facts.packages"
      
      
 
        
        
    
      
