
---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - apt:
        name: vim
    
    - name: Check if vim is installed
      command: dpkg -s vim
      register: dpkg_check
