
---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - apt:
        name: vim
      register: install

    - name: Show Vim installation
      debug:
        msg: "{{ install }}"

    - name: Check if vim is installed
      command: dpkg-query -l vim
      register: deb_check

    - name: Show deb_check
      debug:
        msg: "{{ deb_check }}"
